# Generated by Django 3.0 on 2020-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('S', 'Scan'), ('1', 'Phase 1'), ('2', 'Phase 2'), ('3', 'Phase 3'), ('F', 'Final')], default='Scan', max_length=10),
        ),
    ]
