# Generated by Django 3.0 on 2019-12-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_files_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='docfile',
            field=models.FileField(default='a.txt', upload_to='documents/%Y/%m/%d'),
        ),
    ]
