# Generated by Django 3.0 on 2019-12-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_files_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='docfile',
            field=models.BinaryField(),
        ),
    ]
