# Generated by Django 3.0 on 2019-12-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191230_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='docfile',
        ),
    ]
