# Generated by Django 3.0 on 2019-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_files_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Roles',
            field=models.CharField(choices=[('S', 'Scan'), ('1', 'Phase 1'), ('2', 'Phase 2'), ('3', 'Phase 3'), ('F', 'Final')], default='S', max_length=1),
        ),
    ]
