# Generated by Django 3.0 on 2020-01-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200101_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='files',
            name='Roles',
        ),
    ]
