# Generated by Django 3.0 on 2020-01-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200101_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='role_c',
            field=models.CharField(default='Scan', max_length=200),
        ),
    ]
