# Generated by Django 3.0 on 2020-01-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_role_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='role_c',
            new_name='role',
        ),
    ]
