# Generated by Django 3.0 on 2020-01-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200101_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='upload',
            field=models.FileField(default='false', upload_to='uploads/'),
        ),
    ]
