# Generated by Django 3.0 on 2020-01-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_files_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='upload',
        ),
    ]
