# Generated by Django 3.0 on 2020-01-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_files_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='stage1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='stage2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='stage3',
            field=models.BooleanField(default=False),
        ),
    ]
