# Generated by Django 3.0 on 2020-01-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200102_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='final',
            field=models.CharField(default='False', max_length=7),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stage1',
            field=models.CharField(default='False', max_length=7),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stage2',
            field=models.CharField(default='False', max_length=7),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stage3',
            field=models.CharField(default='False', max_length=7),
        ),
    ]
