# Generated by Django 3.0 on 2020-01-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='files1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.Files'),
            preserve_default=False,
        ),
    ]
