# Generated by Django 3.0 on 2020-01-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_document_files1'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='upload',
            field=models.FileField(default='a.txt', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
