# Generated by Django 3.0 on 2020-01-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200102_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload',
            field=models.FileField(upload_to='images'),
        ),
    ]
