# Generated by Django 3.0 on 2020-01-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200102_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
