# Generated by Django 3.0 on 2020-01-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200102_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload',
            field=models.FileField(default='a.pdf', upload_to='files'),
        ),
    ]
