# Generated by Django 3.0 on 2020-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200102_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
