# Generated by Django 3.0 on 2020-01-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200103_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='upload',
        ),
    ]
