# Generated by Django 3.0 on 2020-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_files_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
